package e_learning_association.project.course;

import e_learning_association.project.category.Category;
import e_learning_association.project.category.CategoryRepository;
import e_learning_association.project.course.dto.CourseResponse;
import e_learning_association.project.course.dto.CreateCourseRequest;
import e_learning_association.project.instructor.InstructorProfile;
import e_learning_association.project.security.AuthUtils;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import java.time.LocalDateTime;

@Service
@Slf4j
@RequiredArgsConstructor
public class CourseServiceImpl implements CourseService{

    private final CourseRepository courseRepository;
    private final CategoryRepository categoryRepository;
    private final CourseMapper courseMapper;

    @Override
    public CourseResponse createCourse(CreateCourseRequest createCourseRequest ) {
        // TODO: write your logic
        // Validate slug
        if (courseRepository.existsBySlug(createCourseRequest.slug())) {
            throw new ResponseStatusException(HttpStatus.CONFLICT,
                    "Slug has already been used");
        }

        // Validate category
        Category category = categoryRepository.findById(createCourseRequest.categoryId())
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
                        "Category has not been found"));

        // Transfer data from DTO to Domain Model
        Course course = courseMapper
                .mapCreateCourseRequestToCourse(createCourseRequest);

        // System data (generated by system)
        course.setCategory(category);
        course.setCountRating(0);
        course.setStarRating(0F);
        course.setIsDeleted(false);
        course.setIsPublished(false);
        course.setCreatedAt(LocalDateTime.now());
        course.setUpdatedAt(LocalDateTime.now());


        JwtAuthenticationToken jwtt = (JwtAuthenticationToken) SecurityContextHolder.getContext().getAuthentication();
        IO.println(jwtt.getToken());
        IO.println(jwtt);
        IO.println(jwtt.getToken().getSubject());

        course.setInstructorProfile(new InstructorProfile(AuthUtils.extractUserId()));

        course = courseRepository.save(course);

        return courseMapper.mapCourseToCourseResponse(course);
    }


    @Override
    public CourseResponse updateCourse(Integer id, CreateCourseRequest createCourseRequest) {

        Course course = courseRepository.findById(id)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND , "course not found") );

        course.setSlug(createCourseRequest.slug());
        course.setKeyword(createCourseRequest.keyword());
        course.setTitle(createCourseRequest.title());
        course.setDescription(createCourseRequest.description());
        course.setThumbnail(createCourseRequest.thumbnail());
        course.setTotalHours(createCourseRequest.totalHours());
        course.setLevel(createCourseRequest.level());
        course.setPrice(createCourseRequest.price());
        course.setDiscountPercent(createCourseRequest.discountPercent());

        Course updated = courseRepository.save(course);

        return courseMapper.mapCourseToCourseResponse(updated);


    }
}
