
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/associate-elearning
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/association_ecommerce_db
    username: postgres
    password: 369369369

  application:
    name: project
server:
  port: 8888
